language: node_js

node_js:
  - "4"
  - "6"

matrix:
  allow_failures:
   - node_js: "6"

services:
 - mongodb
 - redis-server
 - rabbitmq

# after_success:
#   - ./node_modules/.bin/istanbul cover -x "**/spec/**" ./node_modules/.bin/_mocha --report lcovonly -- $(find spec -name '*-spec.js') -R spec
#   - cat ./coverage/lcov.info | node_modules/.bin/coveralls

cache:
    directories:
        - "node_modules"

